var projects = [
	// Название, описание, [категории], ссылка на ленд, ссылка на превью
	// ['','',[''],'','//media.lpgenerator.ru/images/130357/lp-project-.jpg'],
	['GSEA','Участвуй в бизнес-премии GSEA 2015!',['business'],'//design.lpgenerator.ru/klient/biznes/gsea-2015/','//media.lpgenerator.ru/images/130357/lp-project-213.jpg'],
	['EKEN SYNERGY+','Успешный запуск своего бизнеса с нуля',['franchise'],'//design.lpgenerator.ru/klient/franshiza/eken-synergy/','//media.lpgenerator.ru/images/130357/lp-project-62.jpg'],
	['Искатели приключений','Доход свыше 150 000 рублей уже через 2 месяца',['franchise'],'//design.lpgenerator.ru/klient/franshiza/verevochnyij-park/','//media.lpgenerator.ru/images/130357/lp-project-52.jpg'],
	['ЭВРИКА клининг','Уборка офисов и коммерческих помещений в Москве',['services'],'//design.lpgenerator.ru/klient/uslugi/evrika-klining/','//media.lpgenerator.ru/images/130357/lp-project-185.jpg'],
	['ЗАО "ЛК"','Получите надежный и уютный дом Вашей мечты!',['services'],'//design.lpgenerator.ru/klient/uslugi/stroitelstvo-doma/','//media.lpgenerator.ru/images/130357/lp-project-181.jpg'],
	['Врач-косметолог А.Воробьева','Индивидуальные программы c применением профессиональной косметики',['services'],'//design.lpgenerator.ru/klient/uslugi/kosmetolog/','//media.lpgenerator.ru/images/130357/lp-project-164.jpg'],
	['Созидатель','Ремонт и строительство помещений с гарантией 2 года!',['services'],'//design.lpgenerator.ru/klient/uslugi/sozidatel-obschij/','//media.lpgenerator.ru/images/130357/lp-project-163.jpg'],
	['DSCR Project','Экономический расчёт с учетом особенности Вашего бизнеса',['services'],'//design.lpgenerator.ru/klient/uslugi/finanaliz/','//media.lpgenerator.ru/images/130357/lp-project-162.jpg'],
	['Белка','Превратив обычный День рождения в волшебную сказку',['services'],'//design.lpgenerator.ru/klient/uslugi/belka/','//media.lpgenerator.ru/images/130357/lp-project-160.jpg'],
	['Созидатель','Ремонт офиса с выгодой для Вас!',['services'],'//design.lpgenerator.ru/klient/uslugi/sozidatel-ofisyi/','//media.lpgenerator.ru/images/130357/lp-project-159.jpg'],
	['TVOI Tarif - твоя свобода общения','Экономьте до 60% средств на мобильной связи',['services'],'//design.lpgenerator.ru/klient/uslugi/tvoitarif/','//media.lpgenerator.ru/images/130357/lp-project-154.jpg'],
	['BigStom','Стоматологические расходные материалы без посредников',['services'],'//design.lpgenerator.ru/klient/uslugi/stomatologiya/','//media.lpgenerator.ru/images/130357/lp-project-153.jpg'],
	['EXLD service','Ремонт сценического светового оборудования',['services'],'//design.lpgenerator.ru/Klient/uslugi/svet_1/','//media.lpgenerator.ru/images/130357/lp-project-143.jpg'],
	['ПАНОРАМА оконные системы','Качественные окна из натурального материала',['services'],'//design.lpgenerator.ru/klient/uslugi/panorama/','//media.lpgenerator.ru/images/130357/lp-project-141.jpg'],
	['Кто подвезет','Выбирайте водителя и стоимость поездки сами!',['services'],'//design.lpgenerator.ru/klient/uslugi/kto-podvezet/','//media.lpgenerator.ru/images/130357/lp-project-134.jpg'],
	['МОСГОРЦВЕТ','Превратим обычный интерьер в произведение искусства!',['services'],'//design.lpgenerator.ru/klient/uslugi/rospis-inter-graffiti/','//media.lpgenerator.ru/images/130357/lp-project-131.jpg'],
	['VIVALDI симфония праздника','Индивидуальное меню для Вашего мероприятия',['services'],'//design.lpgenerator.ru/klient/uslugi/kejtering/','//media.lpgenerator.ru/images/130357/lp-project-89.jpg'],
	['Imamochki.ru','Химия для быта с доставкой в Новый Уренгой',['services'],'//design.lpgenerator.ru/klient/uslugi/byitovaya-himiya/','//media.lpgenerator.ru/images/130357/lp-project-65.jpg'],
	['Салон "Вельвет"','Индивидуальный пошив штор в Москве и МО',['services'],'//design.lpgenerator.ru/klient/uslugi/shtoryi/','//media.lpgenerator.ru/images/130357/lp-project-59.jpg'],
	['НОКО','Независимая оценка качества образования',['services'],'//design.lpgenerator.ru/klient/uslugi/nezavisimaya-otsenka-kachestva-obrazovaniya/','//media.lpgenerator.ru/images/130357/lp-project-56.jpg'],
	['Carvice','Бесплатно подберем автосервис по ремонту КПП',['services'],'//design.lpgenerator.ru/klient/usligi/remont-akpp/','//media.lpgenerator.ru/images/130357/lp-project-51.jpg'],
	['Russian Business Speakers','Лучшие российские и зарубежные бизнес-ведущие',['services'],'//design.lpgenerator.ru/klient/uslugi/moderatoryi/','//media.lpgenerator.ru/images/130357/lp-project-47.jpg'],
	['REGIS','За 5 дней зарегистрируем ООО или ИП',['services'],'//design.lpgenerator.ru/klient/uslugi/registratsiya-yurlitsa/','//media.lpgenerator.ru/images/130357/lp-project-46.jpg'],
	['DreamLand','Организуем детский день рождения',['services'],'//design.lpgenerator.ru/klient/uslugi/dream-land/','//media.lpgenerator.ru/images/130357/lp-project-44.jpg'],
	['Inalytica','Патентные исследования от «Иналитика»',['services'],'//design.lpgenerator.ru/klient/uslugi/inalitika/','//media.lpgenerator.ru/images/130357/lp-project-41.jpg'],
	['Система ЗАБОТА','Тревожная кнопка для пожилых',['services'],'//design.lpgenerator.ru/klient/uslugi/sistema-zabota/','//media.lpgenerator.ru/images/130357/lp-project-40.jpg'],
	['BABY ITALIA','Создайте благоприятную атмосферу сна для малыша',['product'],'//design.lpgenerator.ru/klient/tovari/baby-italia/','//media.lpgenerator.ru/images/130357/lp-project-104.jpg'],
	['AVS','Автомобильный инвертор AVS от 690 руб.',['product'],'//design.lpgenerator.ru/klient/tovari/avtoinvertoryi/','//media.lpgenerator.ru/images/130357/lp-project-94.jpg'],
	['Книжки-магниты.рф','Увеличим прибыль вашего магазина на 50%',['product'],'//design.lpgenerator.ru/klient/tovari/knizhki-magnityi/','//media.lpgenerator.ru/images/130357/lp-project-88.jpg'],
	['РУКОМ','Скотч, стрейч, перчатки оптом',['product'],'//design.lpgenerator.ru/klient/tovari/upakovochnyie-materialyi/','//media.lpgenerator.ru/images/130357/lp-project-87.jpg'],
	['ЭКОжизнь','Органические продукты питания из Италии оптом!',['product'],'//design.lpgenerator.ru/klient/tovari/organicheskie-produktyi/','//media.lpgenerator.ru/images/130357/lp-project-76.jpg'],
	['Янтарная сосна','Экологичные кухни из 100% массива дерева',['product'],'//design.lpgenerator.ru/klient/tovari/kuhni/','//media.lpgenerator.ru/images/130357/lp-project-74.jpg'],
	['BESTMosaik','Мозаичное панно любой сложности и размеров',['product'],'//design.lpgenerator.ru/klient/tovari/mozaika/','//media.lpgenerator.ru/images/130357/lp-project-70.jpg'],
	['Konica Minolta','Полноцветное МФУ формата А3 по цене чёрно-белого!',['product'],'//design.lpgenerator.ru/klient/tovari/konica-minolta/','//media.lpgenerator.ru/images/130357/lp-project-53.jpg'],
	['Журнал "Дуплет"','Создавайте изысканные вещи своими руками!',['product'],'//design.lpgenerator.ru/klient/tovari/duplet/','//media.lpgenerator.ru/images/130357/lp-project-50.jpg'],
	['Крепежные системы','Оптовые поставки крепежа от производителя',['product'],'//design.lpgenerator.ru/klient/tovari/krepezhnyie-sistemyi-optom/','//media.lpgenerator.ru/images/130357/lp-project-45.jpg'],
	['Label Деловые системы','Производство самоклеящийся этикеток',['product'],'//design.lpgenerator.ru/klient/tovari/etiketki/','//media.lpgenerator.ru/images/130357/lp-project-43.jpg'],
	['Игрушка автобот Bamblebee','Ваш ребенок будет носиться по дому от восторга!',['product'],'//design.lpgenerator.ru/klient/tovari/avtobot-shevrole-kamaro/','//media.lpgenerator.ru/images/130357/lp-project-31.jpg'],
	['HEADWAYSport','Передвигайся налегке, используя гироскутеры!',['product'],'//design.lpgenerator.ru/klient/tovari/giroskuteryi/','//media.lpgenerator.ru/images/130357/lp-project-23.jpg'],
	['AppleCafe','Оригинальным Apple iPhone от 9 900 000 рублей',['product'],'//design.lpgenerator.ru/klient/tovari/iphone/','//media.lpgenerator.ru/images/130357/lp-project-22.jpg'],
	['Магазин аксессуаров Kiel James Patrick','Уникальный мужской браслет ручной работы',['product'],'//design.lpgenerator.ru/klient/tovari/muzhskie-brasletyi/','//media.lpgenerator.ru/images/130357/lp-project-20.jpg'],
	['МТ Цепи','Увеличение производительности вашего предприятия',['product'],'//design.lpgenerator.ru/klient/tovari/prodazha-tsepej/','//media.lpgenerator.ru/images/130357/lp-project-15.jpg'],
	['Школа Скандинавской ходьбы','Похудение и улучшение здоровья',['product'],'//design.lpgenerator.ru/klient/tovari/skandinavskie-palki/','//media.lpgenerator.ru/images/130357/lp-project-8.jpg'],
	['“Инновационные технологии проектирования”','Узнайте, как построить объект в 1,5 раза быстрее',['building'],'//design.lpgenerator.ru/klient/stroitelstvo/bim-proektirovanie/','//media.lpgenerator.ru/images/130357/lp-project-95.jpg'],
	['Milissa Vogue','Выступления и концерты от звезды российской эстрады',['entertainment'],'//design.lpgenerator.ru/klient/razvlechenia/milissa/','//media.lpgenerator.ru/images/130357/lp-project-90.jpg'],
	['Золотая семерка','Качественные окна ПВХ от 999 000 руб./м2',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/okna-zolotaya-semerka/','//media.lpgenerator.ru/images/130357/lp-project-182.jpg'],
	['ПОСМ-РУС','Изготовление POS-материалов по цене на 15-20% ниже рыночной',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/pos-materialyi/','//media.lpgenerator.ru/images/130357/lp-project-49.jpg'],
	['ПОСМ-РУС','Изготовление изделий из оргстекла по цене производителя',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/izdeliya-iz-orgstekla/','//media.lpgenerator.ru/images/130357/lp-project-48.jpg'],
	['Пять из пяти','Федеральный центр подготовки к ЕГЭ и ОГЭ',['education'],'//design.lpgenerator.ru/klient/obuchenie/ege-oge-smolenskaya/','//media.lpgenerator.ru/images/130357/lp-project-206.jpg'],
	['Молодые юристы России','Правозащитный форум “Молодые юристы России”  2015',['education'],'//design.lpgenerator.ru/klient/obuchenie/molodyie-yuristyi/','//media.lpgenerator.ru/images/130357/lp-project-191.jpg'],
	['Молодые юристы России','ФОРУМ “Молодые юристы России”  2015',['education'],'//design.lpgenerator.ru/klient/obuchenie/mur2015ru/','//media.lpgenerator.ru/images/130357/lp-project-180.jpg'],
	['GR технологии','Рекомендации и бизнес-кейсы от первых лиц отрасли',['education'],'//design.lpgenerator.ru/klient/obuchenie/gr/','//media.lpgenerator.ru/images/130357/lp-project-170.jpg'],
	['БЭБИ-Клуб','Подарите малышу успешное будущее, выбрав развивающие программы',['education'],'//design.lpgenerator.ru/klient/obuchenie/babi-klub/','//media.lpgenerator.ru/images/130357/lp-project-169.jpg'],
	['ИМИДЖ-Медия','Конференция "Управление магазином - 2014"',['education'],'//design.lpgenerator.ru/klient/obuchenie/imidzhmedia/','//media.lpgenerator.ru/images/130357/lp-project-130.jpg'],
	['Талантум','Успешная сдача ЕГЭ и поступление на бюджет в лучшие ВУЗы Москвы',['education'],'//design.lpgenerator.ru/klient/obuchenie/talantum/','//media.lpgenerator.ru/images/130357/lp-project-97.jpg'],
	['SPARKLING STAR','Свободно думайте и разговаривайте по-английски',['education'],'//design.lpgenerator.ru/klient/obuchenie/sparkling-star/','//media.lpgenerator.ru/images/130357/lp-project-77.jpg'],
	['SEMENCHUK.COM','Расскажу Вам как создать или продвинуть собственный бизнес',['education'],'//design.lpgenerator.ru/klient/obuchenie/semenchuk/','//media.lpgenerator.ru/images/130357/lp-project-71.jpg'],
	['FINNBLOCK','Теплоизоляционные блоки для строительства дома',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/finnblok/','//media.lpgenerator.ru/images/130357/lp-project-209.jpg'],
	['МариСруб','Собственный дом из оцилиндрованного бревна',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/doma-iz-breven/','//media.lpgenerator.ru/images/130357/lp-project-195.jpg'],
	['Arman de Luxe','Новую квартиру бизнес класса в центре Караганды',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/arman-de-luxe/','//media.lpgenerator.ru/images/130357/lp-project-144.jpg'],
	['Легенда - жилой комплекс','Легендарное качество отделки квартиры от 49 000 руб/м2',['realty'],'//design.lpgenerator.ru/klient/nedvizhimost/krasnodar/','//media.lpgenerator.ru/images/130357/lp-project-133.jpg'],
	['ЭКСПЕРТ','Бесплатная автобусная экскурсия по новостройкам',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/avtobusnyie-turyi-po-novostrojkam-ufyi/','//media.lpgenerator.ru/images/130357/lp-project-96.jpg'],
	['Иркутский центр новостроек','Квартиры в новостройках на 3–15% дешевле, чем у застройщика',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/novostrojki-v-irkutske/','//media.lpgenerator.ru/images/130357/lp-project-24.jpg'],
	['Участки с домами в Подмосковье','Дом с участком от 1 130 000 в Рудаково',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/doma-s-uchastkami/','//media.lpgenerator.ru/images/130357/lp-project-14.jpg'],
	['НОВОСТРОЙ - рады стараться!','Станьте владельцем уютного частного дома от 120 м2',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/novostroj-srub/','//media.lpgenerator.ru/images/130357/lp-project-13.jpg'],
	['МОРТОН','Квартиры в готовых домах на юге Москвы',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/mikrorajon-v-scherbinke/','//media.lpgenerator.ru/images/130357/lp-project-12.jpg'],
	['НОВОСТИ Маркетинга','Как заставить маркетинг приносить клиентов',['events'],'//design.lpgenerator.ru/klient/meropriatia/timur-konferentsiya/','//media.lpgenerator.ru/images/130357/lp-project-109.jpg'],
	['BBCG','Новые возможности для развития бизнеса',['events'],'//design.lpgenerator.ru/klient/meropriatia/sammit/','//media.lpgenerator.ru/images/130357/lp-project-92.jpg'],
	['Единый Центр Присоединения','Подключение водопровода и канализации',['services'],'//design.lpgenerator.ru/klient/uslugi/vodosnabzhenie/','//media.lpgenerator.ru/images/243663/lp-project-179_G5b1TPG.jpg'],
	['WOWBAG','Модульная сумка - создавай новый образ каждый день!',['product'],'//design.lpgenerator.ru/klient/tovari/zhenskie-sumki-wowbag/','//media.lpgenerator.ru/images/243663/lp-project-190_7TjSNDA.jpg'],
	['Jenavi fashion jewellery','Эксклюзивные серьги Амалфи',['product'],'//design.lpgenerator.ru/klient/tovari/sergi-svarovski/','//media.lpgenerator.ru/images/243663/lp-project-188_pW1H4zq.jpg'],
	['MomBook','Уникальный дневник будущей мамочки',['product'],'//design.lpgenerator.ru/klient/tovari/ezhednevnik-dlya-beremennyih/','//media.lpgenerator.ru/images/243663/lp-project-183.jpg'],
	['Spartak','Красивый рельеф в домашних условиях',['product'],'//design.lpgenerator.ru/klient/tovari/turniki/','//media.lpgenerator.ru/images/243663/lp-project-178.jpg'],
	['PL Music','Зажигай под “свежие” треки мировых DJ',['product'],'//design.lpgenerator.ru/klient/tovari/plejlist-c-jc/','//media.lpgenerator.ru/images/243663/lp-project-177.jpg'],
	['TurboSystems','Восстановим турбокомпрессор для любого вида техники',['product'],'//design.lpgenerator.ru/klient/tovari/turbosystems/','//media.lpgenerator.ru/images/243663/lp-project-175.jpg'],
	['ООО "Чейзер"','Мужская сила от Strong man',['product'],'//design.lpgenerator.ru/klient/tovari/preparat-dlya-muzhchin/','//media.lpgenerator.ru/images/243663/lp-project-172.jpg'],
	['FlowerOnline.ru','Цветы с лучших плантаций мира уже через 8 дней',['product'],'//design.lpgenerator.ru/klient/tovari/tsvetyi-optovaya-prodazha/','//media.lpgenerator.ru/images/243663/lp-project-171.jpg'],
	['Хочу пончик!','Доставка ярких угощений по Санкт-Петербургу',['product'],'//design.lpgenerator.ru/klient/tovari/dostavka-ponchikov/','//media.lpgenerator.ru/images/243663/lp-project-168.jpg'],
	['GPS Трекер','Отслеживание объекта с точностью до 5 м',['product'],'//design.lpgenerator.ru/klient/tovari/gps-trekeryi/','//media.lpgenerator.ru/images/243663/lp-project-167.jpg'],
	['WoodStick','Отказ от курения без «насилия» над собой',['product'],'//design.lpgenerator.ru/klient/tovari/sigaretyi/','//media.lpgenerator.ru/images/243663/lp-project-161.jpg'],
	['FAW','Техника европейского качества по доступной цене',['product'],'//design.lpgenerator.ru/klient/tovari/spetstehnika/','//media.lpgenerator.ru/images/243663/lp-project-157.jpg'],
	['Ford','Новый Ford Mondeo с выгодой до 100 000 руб.',['product'],'//design.lpgenerator.ru/klient/tovari/ford/','//media.lpgenerator.ru/images/243663/lp-project-156.jpg'],
	['Fotolabish','Профессиональная выпускная фотокнига',['product'],'//design.lpgenerator.ru/klient/tovari/fotokniga-na-vyipusknoj/','//media.lpgenerator.ru/images/243663/lp-project-152.jpg'],
	['Homes Development Canada','Уникальный каркасный дом по канадской технологии',['building'],'//design.lpgenerator.ru/klient/stroitel\'stvo/karkasnyie-doma/','//media.lpgenerator.ru/images/243663/lp-project-146.jpg'],
	['BARRETT','Обувь Barrett в лучших итальянских традициях c 1917 года',['product'],'//design.lpgenerator.ru/klient/tovari/italyanskaya-obuv/','//media.lpgenerator.ru/images/243663/lp-project-142.jpg'],
	['Элитная парфюмерия из ОАЭ','Насладитесь изысканными и утончёнными ароматами',['product'],'//design.lpgenerator.ru/klient/tovari/parfyum/','//media.lpgenerator.ru/images/243663/lp-project-139.jpg'],
	['irrigate.ru','Системы автоматического полива',['product'],'//design.lpgenerator.ru/klient/tovari/bms/','//media.lpgenerator.ru/images/243663/lp-project-135.jpg'],
	['OMTEX','Жесткие и гибкие технические эндоскопы',['product'],'//design.lpgenerator.ru/klient/tovari/zhestkie-i-gibkie-endoskopyi/','//media.lpgenerator.ru/images/243663/lp-project-129.jpg'],
	['uch-book.ru','Оптовая продажа школьных учебников',['product'],'//design.lpgenerator.ru/klient/tovari/knigi/','//media.lpgenerator.ru/images/243663/lp-project-128.jpg'],
	['gadget','Оригинальная экшн-камера GOPRO HERO3+ BLACK EDITION',['product'],'//design.lpgenerator.ru/klient/tovari/kameryi/','//media.lpgenerator.ru/images/243663/lp-project-125.jpg'],
	['Printer Art','Принтер для печати на ногтях',['product'],'//design.lpgenerator.ru/klient/tovari/printer-art/','//media.lpgenerator.ru/images/243663/lp-project-123.jpg'],
	['Чехлы и тенты для авто','Защитные чехлы-тенты на кузов автомобиля от 3 520 руб.',['product'],'//design.lpgenerator.ru/klient/tovari/chehol-tent-dlya-avto/','//media.lpgenerator.ru/images/243663/lp-project-121.jpg'],
	['Ceremoniya.kz','Лучший выбор пригласительных и свадебных аксессуаров ',['product'],'//design.lpgenerator.ru/klient/uslugi/svadebnaya-tseremoniya/','//media.lpgenerator.ru/images/243663/lp-project-116.jpg'],
	['Вкус жизни','Оптовая поставка начинок для десертов',['product'],'//design.lpgenerator.ru/klient/tovari/konfityur/','//media.lpgenerator.ru/images/243663/lp-project-115.jpg'],
	['Талисмед','Товары для реабилитации животных',['product'],'//design.lpgenerator.ru/klient/tovari/sobachki/','//media.lpgenerator.ru/images/243663/lp-project-110.jpg'],
	['Вкус жизни','Оптовые поставки натурального меда',['product'],'//design.lpgenerator.ru/klient/tovari/optovyie-postavki-myoda/','//media.lpgenerator.ru/images/243663/lp-project-106.jpg'],
	['SilkPlaster','"Подарите себе легкий и быстрый ремонт"',['product'],'//design.lpgenerator.ru/klient/tovari/zhidkie-oboi-obninsk-kaluga/','//media.lpgenerator.ru/images/243663/lp-project-105.jpg'],
	['LEON студия мебели','Станьте обладателем уникальной кухни',['product'],'//design.lpgenerator.ru/klient/tovari/leon-mebel-kuhni/','//media.lpgenerator.ru/images/243663/lp-project-91.jpg'],
	['Shopnebolel.ru','Активатор воды бытовой АП-1, АП-2, АП-3',['product'],'//design.lpgenerator.ru/klient/tovari/aktivator/','//media.lpgenerator.ru/images/243663/lp-project-86.jpg'],
	['Larsen Avantgarde','Летняя ликвидация горных велосипедов',['product'],'//design.lpgenerator.ru/klient/tovari/veliki/','//media.lpgenerator.ru/images/243663/lp-project-54_i7cAsTl.jpg'],
	['Tangle Teezer','Здоровые и красивые волосы от использования расчесок',['product'],'//design.lpgenerator.ru/klient/tovari/prodazha-raschesok/','//media.lpgenerator.ru/images/243663/lp-project-36.jpg'],
	['Чистая среда','Оптовая и розничная продажа мочалок ручной работы',['product'],'//design.lpgenerator.ru/klient/tovari/mochalki/','//media.lpgenerator.ru/images/243663/lp-project-19.jpg'],
	['МиМиДомик','Проведение детских праздников ',['entertainment'],'//design.lpgenerator.ru/klient/razvlechenia/deti/','//media.lpgenerator.ru/images/243663/lp-project-85.jpg'],
	['SKOLKOVO SAILING TEAM','Парусная команда московской школы управления СКОЛКОВО',['entertainment'],'//design.lpgenerator.ru/klient/razvlechenie/yahting/','//media.lpgenerator.ru/images/243663/lp-project-72.jpg'],
	['J-CAMP','Обучение английскому в детском лагере Сочи',['entertainment'],'//design.lpgenerator.ru/klient/razvlechenie/lager-v-sochi/','//media.lpgenerator.ru/images/243663/lp-project-4.jpg'],
	['Фабрика стекла','Изготовление, доставка и монтаж стекольных конструкций',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/fabrika-stekla/','//media.lpgenerator.ru/images/243663/lp-project-93.jpg'],
	['БИЗНЕС БЕЗ ГРАНИЦ','Экспертный анализ перспективных странот руководителей дипломатических миссий',['education'],'//design.lpgenerator.ru/klient/uslugi/biznes-bez-granits/','//media.lpgenerator.ru/images/243663/lp-project-194.jpg'],
	['Аудиотренинг Дианы Щербанской','Аудиотренинг Дианы Щербанской',['education'],'//design.lpgenerator.ru/klient/obuchenie/vernut-muzha/','//media.lpgenerator.ru/images/243663/lp-project-117.jpg'],
	['ФРИИ','"3х-месячная программа по ускоренному развитию интернет-компаний"',['education'],'//design.lpgenerator.ru/klient/obuchenie/akselerator-frii/','//media.lpgenerator.ru/images/243663/lp-project-21.jpg'],
	['todo24','Написание рефератов от 1 дня',['education'],'//design.lpgenerator.ru/klient/obuchenie/kursovyie/','//media.lpgenerator.ru/images/243663/lp-project-2.jpg'],
	['ТИТАН-СТРОЙ','Земельные участки в коттеджных поселках',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/titan-stroj/','//media.lpgenerator.ru/images/243663/lp-project-127.jpg'],
	['ЖК-Летний','Комфортные квартиры в Краснодарском крае',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/zhk-letnij/','//media.lpgenerator.ru/images/243663/lp-project-29.jpg'],
	['РКС','Современные квартиры европейского уровня от 40 000 руб/м2 ',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/penza-nedvizhimost/','//media.lpgenerator.ru/images/243663/lp-project-17.jpg'],
	['Hi-Street','Услуги в сфере работы с коммерческой недвижимостью',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/arenda-pomeschenij/','//media.lpgenerator.ru/images/243663/lp-project-16.jpg'],
	['yogalife','Корпоративные тренинги для повышения продуктивности персонала',['events'],'//design.lpgenerator.ru/klient/meropriatia/korporativnyie-treningi/','//media.lpgenerator.ru/images/243663/lp-project-67.jpg'],
	['Проект “Книги”','Изменим Ваше мировоззрение',['events'],'//design.lpgenerator.ru/klient/meropriatia/proekt-knigi/','//media.lpgenerator.ru/images/243663/lp-project-63.jpg'],
	['ANDERIDA GROUP','Финансовая независимость и приумножение капитала',['events'],'//design.lpgenerator.ru/klient/meropriatia/finansovaya-konsultatsiya/','//media.lpgenerator.ru/images/243663/lp-project-39.jpg'],
	['Mentor TV','Успешный бизнес в странах восточной Африки',['events'],'//design.lpgenerator.ru/klient/meropriatia/stol-afrika/','//media.lpgenerator.ru/images/243663/lp-project-30.jpg'],
	['Вне ЗАВИСИМОСТИ','30-дневный онлайн-курс помощи родственникам алкоголиков',['events'],'//design.lpgenerator.ru/klient/meropriyatie/pomosch-rodstvennikam-alkogolikov/','//media.lpgenerator.ru/images/243663/lp-project-28.jpg'],
	['Онлайн коучинг-марафон Вячеслава Смирнова','Быстрый старт к Энергии и Здоровью 2.0',['events'],'//design.lpgenerator.ru/klient/meropriatia/onlajn-kouching-marafon-vyacheslava-smirnova/','//media.lpgenerator.ru/images/243663/lp-project-1.jpg'],
	['yogalife','Онлайн-тренинг “Саморегуляция 1.0.”',['events'],'//design.lpgenerator.ru/klient/meropriatia/treningi-iskusstvo/','//media.lpgenerator.ru/images/243663/lp-project-1a.jpg'],
	['Asian Brand','Поиск и закупка товаров в Китае',['logistics'],'//design.lpgenerator.ru/klient/logistika/zakupka-tovarov-v-kitae/','//media.lpgenerator.ru/images/243663/lp-project-75.jpg'],
	['Dr Vorobjev','Лечение заикания у детей и взрослых',['health'],'//design.lpgenerator.ru/klient/sdorovie/zaikanie/','//media.lpgenerator.ru/images/243663/lp-project-173.jpg'],
	['BodyMakers','Индивидуальные программы коррекции веса!',['health'],'//design.lpgenerator.ru/klient/zdorovie/korrektsiya-vesa/','//media.lpgenerator.ru/images/243663/lp-project-138.jpg'],
	['Школа шпагата Plastilin','Сесть на шпагат, уже этим летом проще простого!',['health'],'//design.lpgenerator.ru/klient/zdorovie/shpagat/','//media.lpgenerator.ru/images/243663/lp-project-126.jpg'],
	['Академия ортопедии','Избавление от “косточки” на большом пальце ноги',['health'],'//design.lpgenerator.ru/klient/sdorovie/ortopediya/','//media.lpgenerator.ru/images/243663/lp-project-112.jpg'],
	['MAXITE','100% натуральный любовный энергетик',['health'],'//design.lpgenerator.ru/klient/sdorovie/preparat-dlya-udovolstviya/','//media.lpgenerator.ru/images/243663/lp-project-69.jpg'],
	['Кравецкий.рф','Избавление от никотиновой, алкогольной и спайсовой зависимости',['health'],'//design.lpgenerator.ru/klient/sdorovie/kak-brosit-kurit/','//media.lpgenerator.ru/images/243663/lp-project-66.jpg'],
	['WAVEHEAL','Мобильное приложение для здоровья',['health'],'//design.lpgenerator.ru/klient/zdorovie/waveheal/','//media.lpgenerator.ru/images/243663/lp-project-64.jpg'],
	['МЕДИ-Эстетик','Клиника интимной пластики',['health'],'//design.lpgenerator.ru/klient/sdorovie/surgery-labia/','//media.lpgenerator.ru/images/243663/lp-project-6.jpg'],
	['Кредитный брокер в Санкт-Петербурге','10 кредитных программ с выгодными условиями',['credit'],'//design.lpgenerator.ru/klient/kredit/nyij-broker/','//media.lpgenerator.ru/images/243663/lp-project-83.jpg'],
	['СМСфинанс','Заём до 15 000 рублей всего за 30 минут',['credit'],'//design.lpgenerator.ru/klient/kredit/byistryie-zajmyi-onlajn-kompaniya-smsfinans/','//media.lpgenerator.ru/images/243663/lp-project-9.jpg'],
	['Цветы в Сургуте','Изысканные букеты от 700 руб.',['delivery'],'//design.lpgenerator.ru/klient/dostavka/tsvetyi-v-surgute/','//media.lpgenerator.ru/images/243663/lp-project-18.jpg'],
	['TATdelivery','Транспортно-экспедиционные услуги',['trucking'],'//design.lpgenerator.ru/klient/gruzoperevozki/tat/','//media.lpgenerator.ru/images/243663/lp-project-84.jpg'],
	['Boudoir ','Свадебный салон',['wedding'],'//design.lpgenerator.ru/klient/svad\'ba/svadebnyij-salon-buduar/','//media.lpgenerator.ru/images/243663/lp-project-1b.jpg'],
	['Частная бригада мастеров','Отделочные или ремонтные работы любой сложности',['house'],'//design.lpgenerator.ru/klient/vse-dla-doma/remont-kvartir/','//media.lpgenerator.ru/images/243663/lp-project-114.jpg'],
	['Voder','Фильтр VODER для загородного дома',['house'],'//design.lpgenerator.ru/klient/vse-dla-doma/filtr-voder-dlya-zagorodnogo-doma/','//media.lpgenerator.ru/images/243663/lp-project-113.jpg'],
	['ГРЭЙ','Автономная система отопления',['house'],'//design.lpgenerator.ru/klient/vse-dlja-doma/kotlyi/','//media.lpgenerator.ru/images/243663/lp-project-37.jpg'],
	['Система Екей трансфер','Электронная отчетность в контролирующие органы',['bookkeeping'],'//design.lpgenerator.ru/klient/buchuslugi/elektronnaya-otchetnost/','//media.lpgenerator.ru/images/243663/lp-project-73.jpg'],
	['Sanfor','Чистящие средства для дома',['branding'],'//design.lpgenerator.ru/klient/brending/sanfor/','//media.lpgenerator.ru/images/243663/lp-project-11.jpg'],
	['SELA','Бесплатная бонусная карта',['branding'],'//design.lpgenerator.ru/klient/brending/sela/','//media.lpgenerator.ru/images/243663/lp-project-10.jpg'],
	['Один за всех и все за одного','Умная благотворительность',['business'],'//design.lpgenerator.ru/klient/biznes/blagotvoritelnost/','//media.lpgenerator.ru/images/243663/lp-project-176.jpg'],
	['Webtransfer','Инвестирование в микрокредиты',['business'],'//design.lpgenerator.ru/klient/biznes/veb-transfer/','//media.lpgenerator.ru/images/243663/lp-project-158.jpg'],
	['Asfina','Бизнес, недвижимость и ВНЖ в Германии',['business'],'//design.lpgenerator.ru/klient/biznes/biznes-v-germanii/','//media.lpgenerator.ru/images/243663/lp-project-155.jpg'],
	['Центр сертификации','Комплексная оптимизация вашего бизнеса',['business'],'//design.lpgenerator.ru/klient/biznes/sertifikatyi/','//media.lpgenerator.ru/images/243663/lp-project-151.jpg'],
	['АКД','Электронные закупки по 223-ФЗ',['business'],'//design.lpgenerator.ru/klient/biznes/akd/','//media.lpgenerator.ru/images/243663/lp-project-111.jpg'],
	['PROFIT group','Преумножайте свой капитал с пользой',['business'],'//design.lpgenerator.ru/klient/biznes/profit/','//media.lpgenerator.ru/images/243663/lp-project-81.jpg'],
	['Custom Mедиа','Корпоративные СМИ',['audit'],'//design.lpgenerator.ru/klient/audit/custom-media/','//media.lpgenerator.ru/images/243663/lp-project-78.jpg'],
	['Абсолют','Аренда автобусов в Санкт-Петербурге',['transport'],'//design.lpgenerator.ru/klient/transport/transportnaya-kompaniya-absolyut/','//media.lpgenerator.ru/images/243663/lp-project-26.jpg'],
	['ШПИЦБЕРГЕН','Центр Арктического туризма',['tourism'],'//design.lpgenerator.ru/klient/turizm/shpitsbergen/','//media.lpgenerator.ru/images/243663/lp-project-103.jpg'],
	['Aviasales','Дешевые авиабилеты от крупнейших авиакомпаний и агентств',['tourism'],'//design.lpgenerator.ru/klient/turizm/travelpayouts_1/','//media.lpgenerator.ru/images/243663/lp-project-107.jpg'],
	['My Travel Plan','Планировщик путешествий с оффлайн-доступом с мобильного',['tourism'],'//design.lpgenerator.ru/klient/turizm/planirovschik-dlya-otpuska/','//media.lpgenerator.ru/images/243663/lp-project-196.jpg'],
	['А-климат ремонт','Профессиональный ремонт холодильной техники',['services'],'//design.lpgenerator.ru/klient/uslugi/holodilniki/','//media.lpgenerator.ru/images/243663/lp-project-7.jpg'],
	['Anti-chat','Все сообщения с разных каналов связи в одном месте',['services'],'//design.lpgenerator.ru/klient/uslugi/antichat-tp/','//media.lpgenerator.ru/images/243663/lp-project-32.jpg'],
	['ЛОУД И МУВ','Деликатно доставим Ваш груз и освободим от хлопот!',['services'],'//design.lpgenerator.ru/klient/uslugi/gruzchiki/','//media.lpgenerator.ru/images/243663/lp-project-33.jpg'],
	['Nadim CRO','Центр клинических исследований',['services'],'//design.lpgenerator.ru/klient/uslugi/lekarstva/','//media.lpgenerator.ru/images/243663/lp-project-98.jpg'],
	['Организация встреч из роддома ','Индивидуальное оформление вашего праздника',['services'],'//design.lpgenerator.ru/klient/uslugi/roddom/','//media.lpgenerator.ru/images/243663/lp-project-136.jpg'],
	['Центр психологического консультирования','Выявим и устраним проблемы',['services'],'//design.lpgenerator.ru/klient/uslugi/psihologiya/','//media.lpgenerator.ru/images/243663/lp-project-149.jpg'],
	['РеалСтрой','Ремонт под ключ с гарантией 15 лет',['services'],'//design.lpgenerator.ru/klient/uslugi/realstroj/','//media.lpgenerator.ru/images/243663/lp-project-150.jpg'],
	['Центр психологического консультирования ','Избавим от боли несчастной любви',['services'],'//design.lpgenerator.ru/klient/uslugi/kursyi-po-psihologii/','//media.lpgenerator.ru/images/243663/lp-project-165.jpg'],
	['МИРЫ','Франшиза детских развивающих игровых модулей «под ключ»',['franchise'],'//design.lpgenerator.ru/klient/franshiza/drim-miryi/','//media.lpgenerator.ru/images/243663/lp-project-35.jpg'],
	['REWORLD','Приложение на телефон',['legal'],'//design.lpgenerator.ru/klient/yuruslugi/yuristyi/','//media.lpgenerator.ru/images/243663/lp-project-79.jpg'],
	['Юридическая консультация','Юридические услуги в Москве и области',['legal'],'//design.lpgenerator.ru/klient/yuruslugi/yuridicheskie-uslugi_2/','//media.lpgenerator.ru/images/243663/lp-project-80.jpg'],
	['RNConsulting','Налоговая экспертиза вашей компании',['audit'],'//design.lpgenerator.ru/klient/audit/nalogovyij-audit/','//media.lpgenerator.ru/images/243663/lp-project-217.jpg'],
	['Semenchuk.net','Профессиональный консалтинг в сфере бизнеса и инвестиций',['business'],'//design.lpgenerator.ru/klient/biznes/semenchuk-startap/','//media.lpgenerator.ru/images/243663/lp-project-218.jpg'],
	['Optima Logistics','Доставка вашего сборного импортного груза',['trucking'],'//design.lpgenerator.ru/klient/gruzoperevozki/optima-logistics/','//media.lpgenerator.ru/images/243663/lp-project-219.jpg'],
	['ПРОКСИ-Сервис','"Профессиональная Автоматизация ресторана от 70 000 руб."',['automation'],'//design.lpgenerator.ru/klient/avtomatizatchija/tillypad/','//media.lpgenerator.ru/images/243663/lp-project-186.jpg'],
	['Art Lily','Пошив штор на заказ',['house'],'//design.lpgenerator.ru/klient/vse-dlja-doma/shtoryi/','//media.lpgenerator.ru/images/243663/lp-project-27.jpg'],
	['ПОТОЛОК.Center','"Профессиональный монтаж натяжных потолков"',['house'],'//design.lpgenerator.ru/klient/vse-dlja-doma/potolki/','//media.lpgenerator.ru/images/243663/lp-project-58.jpg'],
	['Cascade of colours','Профессиональная косметика высокого качества',['cosmetics'],'//design.lpgenerator.ru/klient/kosmetika/kosmetika-cascade/','//media.lpgenerator.ru/images/243663/lp-project-5.jpg'],
	['ДАО Женщины','Тренинг Натальи Качановой "Самореализация женской Души"',['events'],'//design.lpgenerator.ru/klient/meroprijatia/zhenskij-trening/','//media.lpgenerator.ru/images/243663/lp-project-34.jpg'],
	['Распродажа метров.рф','Самые «горячие» предложения от застройщиков Уфы',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/nedvizhimost-v-g-ufa/','//media.lpgenerator.ru/images/243663/lp-project-25.jpg'],
	['BESTMosaik','Мозаичное панно любой сложности и размеров',['realty'],'//design.lpgenerator.ru/klient/tovari/mozaika/','//media.lpgenerator.ru/images/243663/lp-project-70.jpg'],
	['СП-Серивс','Моментальная замена пустых картриджей на полные',['services'],'//design.lpgenerator.ru/klient/uslugi/kartridzhi/','//media.lpgenerator.ru/images/243663/lp-project-132.jpg'],
	['English friends','Курсы английского языка для детей',['education'],'//design.lpgenerator.ru/klient/obuchenie/english-friends/','//media.lpgenerator.ru/images/243663/lp-project-294.jpg'],
	['Diamond Education','Организуем поступление в лучшие колледжи Англии',['education'],'//design.lpgenerator.ru/klient/obuchenie/obrazovanie-v-anglii/','//media.lpgenerator.ru/images/243663/lp-project-295.jpg'],
	['TURBERY','Персональный подбор программы отдыха в Венгрии',['tourism'],'//design.lpgenerator.ru/klient/turizm/turyi-v-vengriyu/','//media.lpgenerator.ru/images/243663/lp-project-296.jpg'],
	['LITEWELL','Настольная LED лампа SMART LIGHT',['product'],'//design.lpgenerator.ru/klient/tovari/svetodiodnoe-osveschenie/','//media.lpgenerator.ru/images/243663/lp-project-298_3EGdjUK.jpg'],
	['A.R.T. Logistik','Логистическая компания в Китае',['logistics'],'//design.lpgenerator.ru/klient/logistika/logisticheskij-operator/','//media.lpgenerator.ru/images/243663/lp-project-299.jpg'],
	['РУСЭЛЕКТРО','Установка мотор-редуктора BAUER с высоким КПД',['product'],'//design.lpgenerator.ru/klient/tovari/motoryi/','//media.lpgenerator.ru/images/243663/lp-project-300.jpg'],
	['Тренинговый центр Павла Ракова','"Супер эффективный женский тренинг"',['education'],'//design.lpgenerator.ru/klient/obuchenie/pavel-rakov/','//media.lpgenerator.ru/images/243663/lp-project-301.jpg'],
	['Inter Service','Подключение интернета в г. Надым',['services'],'//design.lpgenerator.ru/klient/uslugi/interservice/','//media.lpgenerator.ru/images/243663/lp-project-302.jpg'],
	['АРТ Потолок','Натяжные потолки в Омске и области',['product'],'//design.lpgenerator.ru/klient/tovari/natyazhnyie-potolki-v-omske/','//media.lpgenerator.ru/images/243663/lp-project-303.jpg'],
	['YOGOODLIFE','Онлайн-уроки восточными практиками',['education'],'//design.lpgenerator.ru/klient/obuchenie/yogoodlife/','//media.lpgenerator.ru/images/243663/lp-project-304.jpg'],
	['Strong Link','Полный набор инвестиционных и консалтинговых услуг',['services'],'//design.lpgenerator.ru/klient/uslugi/otsenka-biznesa/','//media.lpgenerator.ru/images/243663/lp-project-305.jpg'],
	['АльфаВымпелПрофи','Надежная охрана вас и вашего бизнеса',['services'],'//design.lpgenerator.ru/klient/uslugi/ohrana/','//media.lpgenerator.ru/images/243663/lp-project-306.jpg'],
	['ФЕРИНГЕР','Печи ЛАМЕЛЬ для русской бани',['product'],'//design.lpgenerator.ru/klient/tovari/pechi/','//media.lpgenerator.ru/images/243663/lp-project-307.jpg'],
	['Margo Mozaique','Постельное белье от производителей',['product'],'//design.lpgenerator.ru/klient/tovari/postelnoe-bele-margo-mozaique/','//media.lpgenerator.ru/images/243663/lp-project-308.jpg'],
	['Центральное Агентство Недвижимости','Земля под жилую застройку в Хабаровске',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/zemelnyij-uchastok-v-habarovske/','//media.lpgenerator.ru/images/243663/lp-project-309.jpg'],
	['INDI design','Разработка дизайна промышленных изделий',['services'],'//design.lpgenerator.ru/klient/uslugi/indi/','//media.lpgenerator.ru/images/243663/lp-project-311.jpg'],
	['СМАРТ ТРАФФИК','1-2-дневные семинары-тренинги от гуру-практиков ',['education'],'//design.lpgenerator.ru/klient/obuchenie/smart-traffik/','//media.lpgenerator.ru/images/243663/lp-project-312.jpg'],
	['СНЕГОДРОМ','Продажа снегоходов YAMAHA',['product'],'//design.lpgenerator.ru/klient/tovari/snegohodyi/','//media.lpgenerator.ru/images/243663/lp-project-313.jpg'],
	['Страховой агент','Подбор оптимального варианта страхования именно для вас',['services'],'//design.lpgenerator.ru/klient/uslugi/strahovoj-agent/','//media.lpgenerator.ru/images/243663/lp-project-314.jpg'],
	['ОСТРИНСКИЙ','Квартира для Вас и Вашей семьи в Краснодаре',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/ostrinskij/','//media.lpgenerator.ru/images/243663/lp-project-315.jpg'],
	['RSLaser','Изготовление изделий с помощью лазерной резки',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/lazernaya-rezka/','//media.lpgenerator.ru/images/243663/lp-project-317.jpg'],
	['Alexander Rena','Услуги фотографа',['services'],'//design.lpgenerator.ru/klient/uslugi/fotograf/','//media.lpgenerator.ru/images/243663/lp-project-318.jpg'],
	['Грузовой эвакуатор','Эвакуация грузового транспорта по Москве и МО',['services'],'//design.lpgenerator.ru/klient/uslugi/evakuatsiya-gruzovogo-transporta/','//media.lpgenerator.ru/images/243663/lp-project-319.jpg'],
	['Экспресс Тендер','Онлайн-сервис «Экспресс Тендер»',['business'],'//design.lpgenerator.ru/klient/biznes/ekspress-tender/','//media.lpgenerator.ru/images/243663/lp-project-320.jpg'],
	['Pravcom','Юридические услуги в Калининграде',['legal'],'//design.lpgenerator.ru/klient/yuruslugi/pravcom/','//media.lpgenerator.ru/images/243663/lp-project-321.jpg'],
	['КАРАТ','Безболезненное исправление прикуса',['health'],'//design.lpgenerator.ru/klient/zdorovie/vrach-ortodont/','//media.lpgenerator.ru/images/243663/lp-project-293.jpg'],
	['Кондиционеры в Алматы','Кондиционеры для дома и офиса от 47 354 тг.',['product'],'//design.lpgenerator.ru/klient/tovari/konditsioneryi-v-almate/','//media.lpgenerator.ru/images/243663/lp-project-292.jpg'],
	['Компания "Прометалл"','Изготовление кованых и сварных металлоизделий',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/metalloizdeliya/','//media.lpgenerator.ru/images/243663/lp-project-291.jpg'],
	['Художественная Студия Виалин','Картины маслом на заказ',['product'],'//design.lpgenerator.ru/klient/tovari/kartinyi-maslom-na-holste/','//media.lpgenerator.ru/images/243663/lp-project-290.jpg'],
	['VlassMaker','Природная густота Ваших волос уже через 1 минуту',['product'],'//design.lpgenerator.ru/klient/tovari/kamuflyazh-dlya-volos/','//media.lpgenerator.ru/images/243663/lp-project-289.jpg'],
	['Бесплатный онлайн вебинар','«Как заработать 5 миллионов за первый год работы в Интернете»',['business'],'//design.lpgenerator.ru/klient/biznes/infobiz/','//media.lpgenerator.ru/images/243663/lp-project-288.jpg'],
	['ZARABOTAT.GURU','Начните зарабатывать на ПАММ счетах прямо сейчас',['business'],'//design.lpgenerator.ru/klient/biznes/pamm/','//media.lpgenerator.ru/images/243663/lp-project-287.jpg'],
	['Летающий спутник','Технологичная игрушка для современных детей',['product'],'//design.lpgenerator.ru/klient/tovari/sputnik/','//media.lpgenerator.ru/images/243663/lp-project-286.jpg'],
	['ОПЭЙ','Официальный консолидатор платежной системы QIWI',['automation'],'//design.lpgenerator.ru/klient/avtomatizatchija/platezhnyie-terminalyi/','//media.lpgenerator.ru/images/243663/lp-project-3.jpg'],
	['"Маша и Медведи"','Эксклюзивная дизайнерская одежда',['product'],'//design.lpgenerator.ru/klient/tovari/odezhda-mim/','//media.lpgenerator.ru/images/243663/lp-project-118.jpg'],
	['go2wheels','Компактные гироскутеры от 29000р.',['product'],'//design.lpgenerator.ru/klient/tovari/giroskuter/','//media.lpgenerator.ru/images/243663/lp-project-145.jpg'],
	['TUTTISZIPPY.RU','Детские модульные коляски',['product'],'//design.lpgenerator.ru/klient/tovari/kolyaski/','//media.lpgenerator.ru/images/243663/lp-project-184.jpg'],
	['Азимут - Центр контроля','Видеонаблюдение "под ключ"',['services'],'//design.lpgenerator.ru/klient/uslugi/arenda-videonablyudeniya/','//media.lpgenerator.ru/images/243663/lp-project-55.jpg'],
	['СПЕЦТЕХЦЕНТР','Аренда спецтехники и логистика',['services'],'//design.lpgenerator.ru/klient/uslugi/spetstehnika-2/','//media.lpgenerator.ru/images/243663/lp-project-57.jpg'],
	['MENTOR TV','Знания лучших экспертов Мира',['services'],'//design.lpgenerator.ru/klient/uslugi/mentor/','//media.lpgenerator.ru/images/243663/lp-project-166.jpg'],
	['M-Magister','Полный спектр юридических услуг',['legal'],'//design.lpgenerator.ru/klient/yuruslugi/yuridicheskie-uslugi/','//media.lpgenerator.ru/images/243663/lp-project-60.jpg'],
	['Optima Logistics','Таможенное оформление и декларирование товара за 2 часа',['logistics'],'//design.lpgenerator.ru/klient/logistika/tamozhennoe-oformlenie/','//media.lpgenerator.ru/images/243663/lp-project-220.jpg'],
	['Московская стекольная мастерская','Окна от производителя со скидкой 25%',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/okna/','//media.lpgenerator.ru/images/243663/lp-project-221.jpg'],
	['Московская стекольная мастерская','Изготовление и установка эксклюзивных стекол',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/zerkala/','//media.lpgenerator.ru/images/243663/lp-project-222.jpg'],
	['FUEL360','Присадка к топливу ',['product'],'//design.lpgenerator.ru/klient/tovari/ekonomiya-topliva/','//media.lpgenerator.ru/images/243663/lp-project-223.jpg'],
	['FanMinicam','Розничная и оптовая продажа мини камер для скрытой съемки',['product'],'//design.lpgenerator.ru/klient/tovari/fan-minicam/','//media.lpgenerator.ru/images/243663/lp-project-364.jpg'],
	['АЙТЕКО','Продажа серверов Cisco UCS',['product'],'//design.lpgenerator.ru/klient/tovari/prodazha-serverov/','//media.lpgenerator.ru/images/243663/lp-project-363.jpg'],
	['Диагностика и лечение','Сеть клиник современной медицины',['health'],'//design.lpgenerator.ru/klient/sdorovie/set-klinik-sovremennoj-meditsinyi/','//media.lpgenerator.ru/images/243663/lp-project-362.jpg'],
	['МЕЗОНИН МЕБЕЛЬ','Детские кровати - чердаки от производителей',['product'],'//design.lpgenerator.ru/klient/tovari/detskie-krovatki/','//media.lpgenerator.ru/images/243663/lp-project-361.jpg'],
	['SMART TRANSLATOR','Устройство голосового перевода',['automation'],'//design.lpgenerator.ru/klient/avtomatizatchija/cmart-perevodchik/','//media.lpgenerator.ru/images/243663/lp-project-360.jpg'],
	['TransTechnoGroup','Доставка грузов по России и СНГ',['trucking'],'//design.lpgenerator.ru/klient/gruzoperevozki/gruzovieperevozki/','//media.lpgenerator.ru/images/243663/lp-project-359.jpg'],
	['ООО "Сервис трейд"','Продажа и производство грузоподъемных строп',['product'],'//design.lpgenerator.ru/klient/tovari/stropyi/','//media.lpgenerator.ru/images/243663/lp-project-358.jpg'],
	['МОРТОН','Продажа квартир в ЖК Влюблино',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/morton-vlyublino/','//media.lpgenerator.ru/images/243663/lp-project-357.jpg'],
	['"Сантехника 5 звезд"','Продажа полотенцесушителей',['product'],'//design.lpgenerator.ru/klient/tovari/prodazha-polotentsesushitelej/','//media.lpgenerator.ru/images/243663/lp-project-356.jpg'],
	['VIP тусы','Сопровождение на VIP тусовки',['services'],'//design.lpgenerator.ru/klient/uslugi/vip-tusyi/','//media.lpgenerator.ru/images/243663/lp-project-355.jpg'],
	['Выкуп недвижимости','Срочный выкуп недвижимости в Москве и Подмосковье',['services'],'//design.lpgenerator.ru/klient/uslugi/vyikup-nedvizhimosti/','//media.lpgenerator.ru/images/243663/lp-project-354.jpg'],
	['"Красный сахар"','Дуэт ведущих на свадьбах',['services'],'//design.lpgenerator.ru/klient/uslugi/duet-veduchih/','//media.lpgenerator.ru/images/243663/lp-project-353.jpg'],
	['РосНДФЛ','Получение имущественного вычета не выходя их дома',['bookkeeping'],'//design.lpgenerator.ru/klient/buhuslugi/rosndflru/','//media.lpgenerator.ru/images/243663/lp-project-352.jpg'],
	['ЭКШН-КАМЕРЫ SJCAM','Оригинальные экш-камеры SJCAM',['product'],'//design.lpgenerator.ru/klient/tovari/ekshn-kamera-prof/','//media.lpgenerator.ru/images/243663/lp-project-351.jpg'],
	['Сияние Сибири','Украшения с якутскими алмазами',['product'],'//design.lpgenerator.ru/klient/tovari/yuvelirnyie-ukrasheniya/','//media.lpgenerator.ru/images/243663/lp-project-350.jpg'],
	['МФТИ, Яндекс','Машинное бучение и анализ данных',['education'],'//design.lpgenerator.ru/klient/obuchenie/bigdata-mfti/','//media.lpgenerator.ru/images/243663/lp-project-349.jpg'],
	['BABOON','Одежда и аксессуары оптом',['product'],'//design.lpgenerator.ru/klient/tovari/odezhda-optom/','//media.lpgenerator.ru/images/243663/lp-project-348.jpg'],
	['Бэби-клуб','Можем раскрыть таланты вашего ребенка',['education'],'//design.lpgenerator.ru/klient/obuchenie/detskij-klub/','//media.lpgenerator.ru/images/243663/lp-project-347.jpg'],
	['Бизнес-миссия в Руанду','Перспективное развитие вашего бизнеса в Африке',['events'],'//design.lpgenerator.ru/klient/meroprijatija/biznes-missiya-v-ruandu/','//media.lpgenerator.ru/images/243663/lp-project-346.jpg'],
	['Quorum','Всероссийский саммит франчайзоров',['events'],'//design.lpgenerator.ru/klient/meroprijatija/sammit-franchajzorov/','//media.lpgenerator.ru/images/243663/lp-project-345.jpg'],
	['HIMMEL','Производство и продажа потолков',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/potolki/','//media.lpgenerator.ru/images/243663/lp-project-344_ywvlgvj.jpg'],
	['A-GROUP','Услуги ликвидаций юридических лиц',['services'],'//design.lpgenerator.ru/klient/uslugi/likvidatsiya-yuridicheskih-lits/','//media.lpgenerator.ru/images/243663/lp-project-343.jpg'],
	['Банный дух','Мобильные бани уже через 14 дней после обращения',['product'],'//design.lpgenerator.ru/klient/tovari/mobilnyie-bani/','//media.lpgenerator.ru/images/243663/lp-project-342.jpg'],
	['Тренинговая компания ООО «АПСЕЛФ»','Обучающий детский лагеть в Крыму',['education'],'//design.lpgenerator.ru/klient/obuchenie/detskij-lager/','//media.lpgenerator.ru/images/243663/lp-project-341.jpg'],
	['Коворкинг на Рижской','Комфортное рабочее место и Wi-Fi всего от 300 руб./день',['services'],'//design.lpgenerator.ru/klient/uslugi/kovorking-na-rizhskoj/','//media.lpgenerator.ru/images/243663/lp-project-340.jpg'],
	['Штаб-Медиа','Сэкономим рекламный бюджет и удвоим количество целевых клиентов',['services'],'//design.lpgenerator.ru/klient/uslugi/shtab-media/','//media.lpgenerator.ru/images/243663/lp-project-339.jpg'],
	['Программы личностного роста','Уникальная система повышения личной эффективности',['education'],'//design.lpgenerator.ru/klient/obuchenie/treningi/','//media.lpgenerator.ru/images/243663/lp-project-338.jpg'],
	['Автоцентр АлмаАвто','Продажа автомобилей в кредит',['transport'],'//design.lpgenerator.ru/Klient/transport/alma-avto/','//media.lpgenerator.ru/images/243663/lp-project-337.jpg'],
	['Артель Русских Мастеров','Авторские ножи и аксессуары ручной работы',['services'],'//design.lpgenerator.ru/klient/uslugi/prodazha-nozhej/','//media.lpgenerator.ru/images/243663/lp-project-336.jpg'],
	['Almaty Management University','Авторские ножи и аксессуары ручной работы',['education'],'//design.lpgenerator.ru/klient/obuchenie/mba/','//media.lpgenerator.ru/images/243663/lp-project-335.jpg'],
	['Systemice hotel service','Проведение выездных деловых мероприятий',['services'],'//design.lpgenerator.ru/klient/uslugi/delovoj-turizm/','//media.lpgenerator.ru/images/243663/lp-project-334.jpg'],
	['URAL','Снабжение оборудованием предприятий промышленной и нефтегазовой отрасли',['services'],'//design.lpgenerator.ru/klient/uslugi/ooo-ural/#main','//media.lpgenerator.ru/images/243663/lp-project-333.jpg'],
	['ФАБРИКА «БАМБУК»','Брендировання одежда с вашим логотипом',['product'],'//design.lpgenerator.ru/klient/tovari/bbpolo/','//media.lpgenerator.ru/images/243663/lp-project-332.jpg'],
	['Dizel\'OK','Прямые продажи дизельного топлива с антипинского НПЗ',['product'],'//design.lpgenerator.ru/klient/tovari/prodazha-dizelya/','//media.lpgenerator.ru/images/243663/lp-project-331.jpg'],
	['Валери EVENT','Планирование и проведение идеальных событий без переплат',['events'],'//design.lpgenerator.ru/klient/meroprijatija/event/','//media.lpgenerator.ru/images/243663/lp-project-330.jpg'],
	['Electric longboard Backfire','Продажа электрических скейтбордов',['product'],'//design.lpgenerator.ru/klient/tovari/elektroskejtyi/','//media.lpgenerator.ru/images/243663/lp-project-329.jpg'],
	['BAELLERRY BUSINESS','Продажа итальянских кожаных клатчей',['product'],'//design.lpgenerator.ru/klient/tovari/baellery/','//media.lpgenerator.ru/images/243663/lp-project-328.jpg'],
	['МОРТОН','Военная ипотека на уникальных условиях',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/morton-voennaya-ipoteka/','//media.lpgenerator.ru/images/243663/lp-project-327.jpg'],
	['ThetaHealing','Эффективная программа, способная изменить жизнь к лучшему!',['events'],'//design.lpgenerator.ru/klient/meroprijatija/theta-healing/','//media.lpgenerator.ru/images/243663/lp-project-326.jpg'],
	['STIEBEL ELTRON','Тепловые насосы ',['product'],'//design.lpgenerator.ru/klient/tovari/shtibel-eltron/','//media.lpgenerator.ru/images/243663/lp-project-325.jpg'],
	['RollsBand','Кавер группа для вашего праздника',['entertainment'],'//design.lpgenerator.ru/klient/razvlechenija/rolls-band/','//media.lpgenerator.ru/images/243663/lp-project-324.jpg'],
	['DEMgroup','Недвижимость в Германии',['realty'],'//design.lpgenerator.ru/klient/nedvigimost/nedvizhimost-v-germanii/','//media.lpgenerator.ru/images/243663/lp-project-323.jpg'],
	['PayQR ','Спасите жизнь за 10 секунд',['business'],'//design.lpgenerator.ru/klient/biznes/payqr/','//media.lpgenerator.ru/images/243663/lp-project-322.jpg'],
	['Turbie Twist','Полотенца из микрофибры',['product'],'//design.lpgenerator.ru/klient/tovari/polotentsa-iz-mikrofibryi/','//media.lpgenerator.ru/images/243663/lp-project-365.jpg'],
	['HI-SHOPPER','Обнови свой гардером с помощью HI-SHOPPER',['automation'],'//design.lpgenerator.ru/klient/avtomatizatchija/prodazha-odezhdyi-v-prilozhenii/','//media.lpgenerator.ru/images/243663/lp-project-366.jpg'],
	['Sweet Beauty','Современный центр косметологии',['health'],'//design.lpgenerator.ru/klient/sdorovie/tsentr-kosmetologii/','//media.lpgenerator.ru/images/243663/lp-project-367.jpg'],
	['СиГор','Дизайн, изготовление и монтаж наружной и интерьерной рекламы',['services'],'//design.lpgenerator.ru/klient/uslugi/naruzhnaya-reklama/','//media.lpgenerator.ru/images/243663/lp-project-368.jpg'],
	['Очки виртуальной реальности','Получите абсолютно новые эмоции с очками вирутальной реальности',['product'],'//design.lpgenerator.ru/klient/tovari/virtualnyie-ochki/','//media.lpgenerator.ru/images/243663/lp-project-369.jpg'],
	['Acoustic calculations','Получите эффективное решение по звукоизоляции и снижению шума в помещении',['services'],'//design.lpgenerator.ru/klient/uslugi/akusticheskie-raschetyi/','//media.lpgenerator.ru/images/243663/lp-project-370.jpg'],
	['1С','Формируйте и сдавайте отчетность без ошибок и штрафов',['services'],'//design.lpgenerator.ru/klient/buhuslugi/1s/','//media.lpgenerator.ru/images/243663/lp-project-371.jpg'],
	['QWERT','Ремонт и обслуживание лазерных принтеров в Москве',['services'],'//design.lpgenerator.ru/klient/uslugi/remont-laz-printerov/','//media.lpgenerator.ru/images/243663/lp-project-372.jpg'],
	['УГОЛЬЭНЕРГО','Атрацит всех сортов напрямую с месторрждений',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/ugol/','//media.lpgenerator.ru/images/243663/lp-project-316.jpg'],
	['ПРОКОМФОРТ','Ремонт квартир в Москве и Московской области',['services'],'//design.lpgenerator.ru/klient/uslugi/remont-kvartir-ofisov-kottedzhej/','//media.lpgenerator.ru/images/243663/lp-project-310.jpg'],
	['Сервис "Кушать подано"','Приготовление ресторанного блюда дома',['services'],'//design.lpgenerator.ru/klient/uslugi/restoran-domaobninsk/','//media.lpgenerator.ru/images/243663/lp-project-285.jpg'],
	['Camperia','Уютный дом на колесах BLUCAMP',['product'],'//design.lpgenerator.ru/klient/tovari/avtodom/','//media.lpgenerator.ru/images/243663/lp-project-284.jpg'],
	['Digital diesel','Автосканер MaxiSys Mini',['product'],'//design.lpgenerator.ru/klient/tovari/dizel/','//media.lpgenerator.ru/images/243663/lp-project-283.jpg'],
	['РОСТОК','Мини детский сад индивидуального развития',['education'],'//design.lpgenerator.ru/klient/obuchenie/detskij-sadik/','//media.lpgenerator.ru/images/243663/lp-project-282.jpg'],
	['Колокейшн в Дата-Центрах Москвы','Размещение своих серверов на колокейшн',['services'],'//design.lpgenerator.ru/klient/uslugi/kolokejshn-v-data-tsentrah-moskvyi/','//media.lpgenerator.ru/images/243663/lp-project-281.jpg'],
	['VIP-TRIPS','4-х дневный тур в Италию',['tourism'],'//design.lpgenerator.ru/klient/turism/darim-emotsii-stan-millionerom/','//media.lpgenerator.ru/images/243663/lp-project-280.jpg'],
	['Baboon','Галстуки-бабочки ручной работы',['product'],'//design.lpgenerator.ru/klient/tovari/galstuki-babochki/','//media.lpgenerator.ru/images/243663/lp-project-279.jpg'], 
	['КАДРотека','Выездная фотостудия',['services'],'//design.lpgenerator.ru/klient/uslugi/fotostudiya/','//media.lpgenerator.ru/images/243663/lp-project-278.jpg'],
	['HDDD.RU','Диагностика носителя и восстановление утерянной информации',['services'],'//design.lpgenerator.ru/klient/uslugi/vosstanovlenie-dannyih/','//media.lpgenerator.ru/images/243663/lp-project-277.jpg'],
	['Bags Boutique','Брендовые сумочки оригинального качества',['product'],'//design.lpgenerator.ru/klient/tovari/sumki/','//media.lpgenerator.ru/images/243663/lp-project-276.jpg'],
	['STN','Подберем лучший вариант проживания в Санкт-Петербурге',['services'],'//design.lpgenerator.ru/klient/uslugi/apartamentyi-v-pitere/','//media.lpgenerator.ru/images/243663/lp-project-275.jpg'],
	['АНТИРАБСТВО','Курс, как правильно составить резюме',['education'],'//design.lpgenerator.ru/klient/obuchenie/vsyo-o-trudoustrojstve/','//media.lpgenerator.ru/images/243663/lp-project-274.jpg'],
	['Академия моды и стиля','Онлайн курс, как быть стильной и вызывать восхищение',['education'],'//design.lpgenerator.ru/klient/obuchenie/sovetyi-stilista/','//media.lpgenerator.ru/images/243663/lp-project-273.jpg'],
	['Адвокатское бюро «Атлант»','Полный комплекс юридических услуг ',['legal'],'//design.lpgenerator.ru/klient/yuruslugi/advokatskoe-byuro-atlant/','//media.lpgenerator.ru/images/243663/lp-project-272_z7StfqC.jpg'],
	['Центр Автотехнической Экспертизы','Экспертиза. Оценка ущерба. Юридическое сопровождение',['services'],'//design.lpgenerator.ru/klient/uslugi/avtostrahovanie/','//media.lpgenerator.ru/images/243663/lp-project-271.jpg'],
	['Авторские решения','Экспертиза. Оценка ущерба. Юридическое сопровождение',['services'],'//design.lpgenerator.ru/klient/uslugi/avtorskie-resheniya/','//media.lpgenerator.ru/images/243663/lp-project-270.jpg'],
	['Школа классической йоги','Обретите гармонию души и тела',['health'],'//design.lpgenerator.ru/klient/sdorovie/joga-shkolajogirf/','//media.lpgenerator.ru/images/243663/lp-project-269.jpg'],
	['Автоломбард','Оформление кредита под залог автомобиля',['services'],'//design.lpgenerator.ru/klient/uslugi/avtolombard/','//media.lpgenerator.ru/images/243663/lp-project-268.jpg'],
	['AUTO-PARTS','Получите 3 выгодных предложения по запчастям',['product'],'//design.lpgenerator.ru/klient/tovari/avtozapchasti/','//media.lpgenerator.ru/images/243663/lp-project-267.jpg'],
	['AUTO-PARTS','Оригинальные автозапчасти оптом',['product'],'//design.lpgenerator.ru/klient/tovari/avtozapchasti-optom/','//media.lpgenerator.ru/images/243663/lp-project-266.jpg'],
	['Tower-investment-fund','Увеличиим ваши инвестиции на Валютном, Фондовом и рынке Фьючерсов',['product'],'//design.lpgenerator.ru/klient/biznes/tower-investment-fund/','//media.lpgenerator.ru/images/243663/lp-project-265.jpg'],
	['SMM','Практический курс по продвижению в соц.сетях',['events'],'//design.lpgenerator.ru/klient/meroprijatie/smm-prakticheskij-kurs-za-30-dnej/','//media.lpgenerator.ru/images/243663/lp-project-264.jpg'],
	['b2broker','Создайте успешный брокерский бизнес с нуля',['franchise'],'//design.lpgenerator.ru/klient/franshiza/b2broker/','//media.lpgenerator.ru/images/243663/lp-project-263.jpg'],
	['К-Сервис','Сетевое оборудование',['product'],'//design.lpgenerator.ru/klient/tovari/it-oborudovanie/','//media.lpgenerator.ru/images/243663/lp-project-262.jpg'],
	['Ideal-foot','Стельки для исправления стопы',['product'],'//design.lpgenerator.ru/klient/tovari/ideal-foot/','//media.lpgenerator.ru/images/243663/lp-project-261.jpg'],
	['Bz-studio','Рекламные видео-ролики под ключ',['services'],'//design.lpgenerator.ru/klient/uslugi/bz-studio/','//media.lpgenerator.ru/images/243663/lp-project-260.jpg'],
	['SOLAR events','Вау-семинар Игоря Манна',['events'],'//design.lpgenerator.ru/klient/meroprijatie/vau-seminar-igorya-manna-client-driven/','//media.lpgenerator.ru/images/243663/lp-project-259.jpg'],
	['ARDNUS','Продажа компьютеров Ardnus',['product'],'//design.lpgenerator.ru/klient/tovari/buryij/','//media.lpgenerator.ru/images/243663/lp-project-258.jpg'],
	['ГРОЗА','Узнайте о приближении гроз заранее',['services'],'//design.lpgenerator.ru/klient/uslugi/grozopelengatsiya/','//media.lpgenerator.ru/images/243663/lp-project-256.jpg'],
	['VIZANTIYA-ART','Ювелирные украшения из серебра с эмалью',['product'],'//design.lpgenerator.ru/klient/tovari/yuvelirnyie-izdeliya/','//media.lpgenerator.ru/images/243663/lp-project-255.jpg'],
	['Приусадебное хозяйство "Николо-Рожок"','Выращиваем ягненка для вас',['services'],'//design.lpgenerator.ru/klient/uslugi/prodazha-baraninyi/','//media.lpgenerator.ru/images/243663/lp-project-254.jpg'],
	['Благотворительный Фонд','Участвуйте в благотворительной акции',['business'],'//design.lpgenerator.ru/klient/biznes/orden/','//media.lpgenerator.ru/images/243663/lp-project-253.jpg'],
	['ООО «АкваТекс»','Установка локального очистного сооружения',['house'],'//design.lpgenerator.ru/klient/vse-dlja-doma/vodoochistitelnyie-kanalyi/','//media.lpgenerator.ru/images/243663/lp-project-251.jpg'],
	['ООО «АКС - Групп»','Утилизации бытовых стоков',['house'],'//design.lpgenerator.ru/klient/vse-dlja-doma/ochistitelnyie-sooruzheniya/','//media.lpgenerator.ru/images/243663/lp-project-250.jpg'],
	['QUMO','Компактный внешний аккумулятор',['product'],'//design.lpgenerator.ru/klient/tovari/qumo-fleshka/','//media.lpgenerator.ru/images/243663/lp-project-249.jpg'],
	['ПЕРВОИСТОЧНИК','Система отопления европейского качества',['house'],'//design.lpgenerator.ru/klient/vse-dlja-doma/pervoistochnik/','//media.lpgenerator.ru/images/243663/lp-project-248.jpg'],
	['Душ Алексеева','Избавьтесь от усталости и стресса за 1 день',['product'],'//design.lpgenerator.ru/klient/tovari/dush-alekseeva-dlya-pozhilyih-lyudej/','//media.lpgenerator.ru/images/243663/lp-project-247.jpg'],
	['СРО','Оформление допуска СРО без договора займа',['services'],'//design.lpgenerator.ru/klient/uslugi/sro/','//media.lpgenerator.ru/images/243663/lp-project-246.jpg'],
	['Стенды Техно Вектор','Доступное оборудование для сход-развала',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/tehno-vektor/','//media.lpgenerator.ru/images/243663/lp-project-245.jpg'],
	['Tender Prof','Сопровождение тендеров и аутсорсинг тендерных отделов',['business'],'//design.lpgenerator.ru/klient/biznes/tenderprof/','//media.lpgenerator.ru/images/243663/lp-project-244.jpg'],
	['СОКОЛОВО','Загородные дома в поселке “Соколово”',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/kottedzhi-sokolovo/','//media.lpgenerator.ru/images/243663/lp-project-243.jpg'],
	['Alfa-service','Клининг по-умному',['services'],'//design.lpgenerator.ru/klient/uslugi/alfaintruold/','//media.lpgenerator.ru/images/243663/lp-project-241.jpg'],
	['Smart Scribe','Рисованное видео для роста вашего бизнеса',['services'],'//design.lpgenerator.ru/klient/uslugi/risovannoe-video/','//media.lpgenerator.ru/images/243663/lp-project-240.jpg'],
	['Аудиторская компания РОСТ','Профессиональное бухгалтерское обслуживание',['audit'],'//design.lpgenerator.ru/klient/audit/auditorskaya-kompaniya-rost/','//media.lpgenerator.ru/images/243663/lp-project-239.jpg'],
	['Multimediaprom','Видеореклама и продающее видео',['services'],'//design.lpgenerator.ru/klient/uslugi/reklamnyie-roliki-multimediaprom/','//media.lpgenerator.ru/images/243663/lp-project-238.png'],
	['ГосБух','Улучшим работу системы 1С',['bookkeeping'],'//design.lpgenerator.ru/klient/buhuslugi/gosbuh/','//media.lpgenerator.ru/images/243663/lp-project-237.png'],
	['Профессиональные бухгалтерские услуги','Переводим с бухгалтерского на «человеческий» и обратно',['bookkeeping'],'//design.lpgenerator.ru/klient/buhuslugi/professionalnyie-buhgalterskie-uslugi/','//media.lpgenerator.ru/images/243663/lp-project-236.jpg'],
	['Amaru-trans','Грузоперевозки в Казахстан',['trucking'],'//design.lpgenerator.ru/klient/gruzoperevozki/gruzoperevozki-v-kazahstan/','//media.lpgenerator.ru/images/243663/lp-project-235.jpg'],
	['NextGeneration','Контейнерные перевозки морским, воздушным и наземным путем',['trucking'],'//design.lpgenerator.ru/klient/gruzoperevozki/gruzoperevozki/','//media.lpgenerator.ru/images/243663/lp-project-234.jpg'],
	['Лес друзей','Находите новых друзей, присоединившись к нашему сообществу',['events'],'//design.lpgenerator.ru/klient/meroprijatia/les-druzej/','//media.lpgenerator.ru/images/243663/lp-project-232.jpg'],
	['Лизинг за 1 день','"Mercedes-Benz быстрый и удобный лизинг"',['credit'],'//design.lpgenerator.ru/klient/kredit/mersedes-v-lizing/','//media.lpgenerator.ru/images/243663/lp-project-231.jpg'],
	['ПРОММАШ','Продажа строительной техники DOOSAN',['transport'],'//design.lpgenerator.ru/klient/transport/stroitelnaya-tehnika-doosan/','//media.lpgenerator.ru/images/243663/lp-project-230.jpg'],
	['Bodyflex&Oxycise','Центр красоты и стойности Антонины Кравец',['health'],'//design.lpgenerator.ru/klient/zdorovie/tsentr-bodyflex-and-oxycise/','//media.lpgenerator.ru/images/243663/lp-project-229.jpg'],
	['INTERGAZ','Система отопления на сжиженном газе',['house'],'//design.lpgenerator.ru/klient/vse-dlja-doma/intergaz-ru/','//media.lpgenerator.ru/images/243663/lp-project-228.jpg'],
	['InCaPol','Устройство полимерных полов по финским технологиям',['product'],'//design.lpgenerator.ru/klient/tovari/polimernyie-finskie-polyi/','//media.lpgenerator.ru/images/243663/lp-project-227.jpg'],
	['Макси ФЛОРА','Услуги ландшафтного дизайна',['services'],'//design.lpgenerator.ru/klient/uslugi/landshaftnyij-dizajn/','//media.lpgenerator.ru/images/243663/lp-project-226.jpg'],
	['Stroy Good','Оптовые поставки газоблоков',['product'],'//design.lpgenerator.ru/klient/tovari/gazobloki/','//media.lpgenerator.ru/images/243663/lp-project-225.jpg'],
	['ТичьСпич','Центр развития и коррекции речи',['education'],'//design.lpgenerator.ru/klient/obuchenie/razvitie-rechi/','//media.lpgenerator.ru/images/243663/lp-project-224.jpg'],
	['Мебелитто','Кухни на заказ от производителя',['product'],'//design.lpgenerator.ru/klient/tovari/kuchni_na_zakaz/','//media.lpgenerator.ru/images/243663/lp-project-373.jpg'],
	['Мастер-алкомастер','Качественные алкогольные напитки в домашних условиях',['product'],'//design.lpgenerator.ru/klient/tovari/samogonnyij-apparat/','//media.lpgenerator.ru/images/243663/lp-project-374.jpg'],
	['Wooder','Изготовление дерево-алюминиевых террас по немецким технологиям',['product'],'//design.lpgenerator.ru/klient/tovari/derevyannyie-okna/','//media.lpgenerator.ru/images/243663/lp-project-375.jpg'],
	['Madal Bal','Очистка организма и похудение по швейцарской программе',['product'],'//design.lpgenerator.ru/klient/tovari/madal-bal/','//media.lpgenerator.ru/images/243663/lp-project-376.jpg'],
	['Fashion Week on-line shop','Эксклюзивные копии одежды от FASHIONWEEK',['fashion'],'//design.lpgenerator.ru/klient/moda-i-stil/moda/','//media.lpgenerator.ru/images/302493/lp-project-61.jpg'],
	['Great Moscow Show','Самые заметные Hip-Hop/Soul/R&B/Jazz исполнители на одной сцене',['entertainment'],'//design.lpgenerator.ru/klient/razvlechenia/vecherinki/','//media.lpgenerator.ru/images/302493/lp-project-119.jpg'],
	['Народный септик','Автономные канализации в СПб и Ленинградской области',['product'],'//design.lpgenerator.ru/klient/tovari/septiki-v-spb/','//media.lpgenerator.ru/images/303631/lp-project-378.jpg'],
	['Лагуна Юг','Комплекс отдыха и развлечений на Горьковском море',['services'],'//design.lpgenerator.ru/klient/uslugi/laguna-yug/','//media.lpgenerator.ru/images/303631/lp-project-379.jpg'],
	['Mango','Палки Mango для скандинавской ходьбы',['product'],'//design.lpgenerator.ru/klient/tovari/palkimango/','//media.lpgenerator.ru/images/303631/lp-project-380.jpg'],
	['Мой щенок','Продажа щенков в Москве, Санкт-Петербурге и области',['product'],'//design.lpgenerator.ru/klient/tovari/moj-schenok/','//media.lpgenerator.ru/images/303631/lp-project-381.jpg'],
	['Scincare','Тканевые маски из Японии',['product'],'//design.lpgenerator.ru/klient/tovari/tkanevyie-maski-dlya-litsa/','//media.lpgenerator.ru/images/303631/lp-project-382.jpg'],
	['Ведущий на свадьбу, корпоративы, юбилеи','Проведение свадеб и праздников в Москве и Санкт-Петербурге',['services'],'//design.lpgenerator.ru/klient/uslugi/veduschij/','//media.lpgenerator.ru/images/303631/lp-project-383.jpg'],
	['Антирабство','Профориентация для взрослых',['education'],'//design.lpgenerator.ru/klient/obuchenie/antirabstvo-proforientatsiya/','//media.lpgenerator.ru/images/303631/lp-project-384.jpg'],
	['Антирабство','Онлайн-курс "Юридическая помощь"',['education'],'//design.lpgenerator.ru/klient/obuchenie/antirabstvo-yuridicheskaya-pomosch/','//media.lpgenerator.ru/images/303631/lp-project-385.jpg'],
	['Антирабство','Онлайн-курсы от "Антирабства"',['education'],'//design.lpgenerator.ru/klient/obuchenie/antirabstvo/','//media.lpgenerator.ru/images/303631/lp-project-386.jpg'],
	['ARVizio','Доставка очков виртуальной реальности по всей России от 3-х дней!',['product'],'//design.lpgenerator.ru/klient/tovari/virtualnaya-realnost/','//media.lpgenerator.ru/images/303631/lp-project-387.jpg'],
	['Smart Baby Watch','Доставка детских оригинальных GPS-часов по всей России!',['product'],'//design.lpgenerator.ru/klient/tovari/chasyi-s-gps-trekerom/','//media.lpgenerator.ru/images/303631/lp-project-388.jpg'],
	['КОМБОЛИФТ','Австрийские поручни для эскалаторов',['product'],'//design.lpgenerator.ru/klient/tovari/poruchni/','//media.lpgenerator.ru/images/303631/lp-project-389.jpg'],
	['МОРТОН','Новостройки Москвы',['realty'],'//design.lpgenerator.ru/klient//nedvizimost/novostrojki-moskvyi/','//media.lpgenerator.ru/images/303631/lp-project-390.jpg'],
	['КАРАТ','Продажа оборудования для пивоварен',['product'],'//design.lpgenerator.ru/klient/tovari/prodagja-pivnogo-oborudovaniya/','//media.lpgenerator.ru/images/303631/lp-project-391.jpg'],
	['Свободное сердце','Выйти замуж за иностранца',['services'],'//design.lpgenerator.ru/klient/uslugi/svobodnoeserdze/','//media.lpgenerator.ru/images/303631/lp-project-392.jpg'],
	['NanoCeramica','Защити автомобиль от царапин, сколов и грязи',['product'],'//design.lpgenerator.ru/klient/tovari/nanokeramika/','//media.lpgenerator.ru/images/303631/lp-project-393.jpg'],
	['Печатный цех "Клякса"','Печать фотообоев на заказ',['services'],'//design.lpgenerator.ru/klient/uslugi/pechatnyij-tseh-klyaksa/','//media.lpgenerator.ru/images/303631/lp-project-394.jpg'],
	['МОРТОН','Вебинары от компании "Мортон"',['education'],'//design.lpgenerator.ru/klient/obuchenie/vebinaryi-kompanii-morton/','//media.lpgenerator.ru/images/303631/lp-project-395.jpg'],
	['МОРТОН','Однокомнатные квартиры и студии в Москве и МО',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/odnushki-morton/','//media.lpgenerator.ru/images/303631/lp-project-396.jpg'],
	['Inter Service','Аренда систем видеонаблюдения',['services'],'//design.lpgenerator.ru/klient/uslugi/videonablyudenie/','//media.lpgenerator.ru/images/303631/lp-project-397.jpg'],
	['MOS-PEREPLET.RU','Архивная компания',['services'],'//design.lpgenerator.ru/klient/uslugi/arhivnaya-kompaniya/','//media.lpgenerator.ru/images/303631/lp-project-398.jpg'],
	['STEKLO.RU','Конструкции из закаленного стекла',['product'],'//design.lpgenerator.ru/klient/tovari/stekljannie-peregorodki/','//media.lpgenerator.ru/images/303631/lp-project-399.jpg'],
	['YUYDEMIN Tea House','Стеклянный чайник с кнопкой Kamjove от лучших мастеров Китая',['product'],'//design.lpgenerator.ru/klient/tovari/zavarochnyie-chajniki/','//media.lpgenerator.ru/images/303631/lp-project-400.jpg'],
	['WhyWhy','Интерактивные книги для детей от 3 до 8 лет',['product'],'//design.lpgenerator.ru/klient/tovari/detskie-elektronnyie-knigi/','//media.lpgenerator.ru/images/303631/lp-project-401.jpg'],
	['Konica Minolta','Полноцветные МФУ bizhub C258 формата SRА3',['product'],'//design.lpgenerator.ru/klient/tovari/bizhubc258/','//media.lpgenerator.ru/images/303631/lp-project-402.jpg'],
	['Театр-студия','Театральная студия для взрослых',['education'],'//design.lpgenerator.ru/klient/obuchenie/akteryi/','//media.lpgenerator.ru/images/303631/lp-project-403.jpg'],
	['YogaMammy','Коррекция диастаза после родов',['health'],'//design.lpgenerator.ru/klient/sdorovie/onlajn-marafon-korrektsii-diastaza-posle-rodov-yogamammy/','//media.lpgenerator.ru/images/303631/lp-project-404.jpg'],
	['Artix Оконные системы','Продажа и монтаж окон от 3 до 7 дней',['product'],'//design.lpgenerator.ru/klient/tovari/okna-artiks/','//media.lpgenerator.ru/images/303631/lp-project-405.jpg'],
	['Экшн камера SJ9000PRO','Продажа экшн-камеры с бесплатной доставкой по России',['product'],'//design.lpgenerator.ru/klient/tovari/ekshen-kameryi/','//media.lpgenerator.ru/images/303631/lp-project-406.jpg'],
	['СтолБери','Продажа столов и стульев в Санкт-Петербурге',['product'],'//design.lpgenerator.ru/klient/tovari/ctolyi-i-stulya/','//media.lpgenerator.ru/images/303631/lp-project-407.jpg'],
	['CDEK','Доставка документов и грузов по России',['services'],'//design.lpgenerator.ru/klient/uslugi/sdek/','//media.lpgenerator.ru/images/303631/lp-project-408.jpg'],
	['СпрефиксРус','Изоляция методом напыления',['services'],'//design.lpgenerator.ru/klient/uslugi/izolyatsiya-metodom-napyileniya/','//media.lpgenerator.ru/images/303631/lp-project-409.jpg'],
	['BestWay','Жилищниый кооператив Best Way',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/zhilischnyij-kooperativ/','//media.lpgenerator.ru/images/303631/lp-project-410.jpg'],
	['МИДИНВЕСТ','Займ под залог недвижимости',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/zajm-pod-zalog-nedvizhimosti/','//media.lpgenerator.ru/images/303631/lp-project-413.jpg'],
	['AIRWEB','Настройка и ведение контекстной рекламы',['services'],'//design.lpgenerator.ru/klient/uslugi/airweb/','//media.lpgenerator.ru/images/303631/lp-project-414.jpg'],
	['Iiko Discount','Автоматизация ресторанов на Iiko',['automation'],'//design.lpgenerator.ru/klient/avtomatizatchija/avtomatizatsiya-restoranov/','//media.lpgenerator.ru/images/301342/lp-project-415.jpg'],
	['Proff-tehnika','Комплексное оснащение баров, ресторанов и магазинов',['product'],'//design.lpgenerator.ru/klient/tovari/proff-tehnika/','//media.lpgenerator.ru/images/301342/lp-project-416.jpg'],
	['Lifeaddwiser','Ваш личный диджитал- наставник по улучшению жизни',['automation'],'//design.lpgenerator.ru/klient/avtomatizatchija/Lifeaddwiser/','//media.lpgenerator.ru/images/301342/lp-project-417.jpg'],
	['SUN LINE','Создание гармоничного интерьера в вашем доме',['product'],'//design.lpgenerator.ru/klient/tovari/sun-line/','//media.lpgenerator.ru/images/301342/lp-project-418.jpg'],
	['BARDOT','Салон красоты в Бутово',['services'],'//design.lpgenerator.ru/klient/uslugi/bardot/','//media.lpgenerator.ru/images/301342/lp-project-419.jpg'],
	['Кухни «Латтеа»','Производство кухни из натурального дерева',['product'],'//design.lpgenerator.ru/klient/tovari/kuhni-lattea/','//media.lpgenerator.ru/images/301342/lp-project-420.jpg'],
	['Летняя резиденция','Жилой комплекс в Сочи',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/rks-sochi/','//media.lpgenerator.ru/images/301342/lp-project-421.jpg'],
	['Dizel\'ok','Авто и ж/д поставки дизельного топлива',['product'],'//design.lpgenerator.ru/klient/tovari/dizelnoe-toplivo/','//media.lpgenerator.ru/images/301342/lp-project-422.jpg'],
	['RINCH marketing','Разработка и реализация маркетинговых решений',['services'],'//design.lpgenerator.ru/klient/uslugi/rinch/','//media.lpgenerator.ru/images/301342/lp-project-423.jpg'],
	['Автошкола Таксопарк','Обучение уверенному вождению за 2,5 месяца',['services'],'//design.lpgenerator.ru/klient/uslugi/avtoshkola-taksopark/','//media.lpgenerator.ru/images/301342/lp-project-424.jpg'],
	['Мегаплан','Система автоматизации бизнеса',['automation'],'//design.lpgenerator.ru/klient/avtomatizatchija/megaplan/','//media.lpgenerator.ru/images/301342/lp-project-425.jpg'],
	['ИНЖПЛАСТ','Трубы ПНД от производителя с доставкой за 24 часа по Москве и МО',['product'],'//design.lpgenerator.ru/klient/tovari/trubyi-izhplast/','//media.lpgenerator.ru/images/301342/lp-project-426.jpg'],
	['H.O.P.E.','Благотворительная компания H.O.P.E.',['business'],'//design.lpgenerator.ru/klient/biznes/hope-russkij/','//media.lpgenerator.ru/images/301342/lp-project-427.jpg'],
	['Inevitable success rus','Семинар по технике запоминания с Домиником Обрайеном в Цюрихе',['education'],'//design.lpgenerator.ru/klient/obuchenie/inevitable-success/','//media.lpgenerator.ru/images/301342/lp-project-428.jpg'],
	['ЖК "Мичуринский"','Жилой комплекс в Твери',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/zhk-michurinskij/','//media.lpgenerator.ru/images/301342/lp-project-429.jpg'],
	['BestWay','Жилищный коопертив',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/zhk-best-vej/','//media.lpgenerator.ru/images/301342/lp-project-430.jpg'],
	['Махаон','Студия ландшафтного дизайна в Санкт-Петербурге и области',['building'],'//design.lpgenerator.ru/klient/stroitel\'stvo/mahaon/','//media.lpgenerator.ru/images/301342/lp-project-431.jpg'],
	['Мотошкола Старт','Мотошкола Старт в Москве',['education'],'//design.lpgenerator.ru/klient/obuchenie/motoshkola/','//media.lpgenerator.ru/images/301342/lp-project-432.jpg'],
	['Nissan','Дилерский центр Nissan Кунцево',['transport'],'//design.lpgenerator.ru/klient/tovari/atts-kuntsevo/','//media.lpgenerator.ru/images/301342/lp-project-433.jpg'],
	['Меридиан Транс Карго','Авиаперевозки груза из Домодедово по России',['trucking'],'//design.lpgenerator.ru/klient/gruzoperevozki/aviaperevozki/','//media.lpgenerator.ru/images/301342/lp-project-434.jpg'],
	['Бэби-клуб','Детский развивающий центр',['services'],'//design.lpgenerator.ru/klient/uslugi/detskij-razvivayuschij-tsentr/','//media.lpgenerator.ru/images/301342/lp-project-435.jpg'],
	['ORANGE life solutions','Доступная недвижимость Северного Кипра',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/nedvizhimost-na-kipre-konkretnyij-obekt/','//media.lpgenerator.ru/images/303631/lp-project-411_iQwLCBx.jpg'],
	['EUROCARD','Производство пластиковых карт',['production'],'//design.lpgenerator.ru/klient/proizvodstvo/eurocard/','//media.lpgenerator.ru/images/303631/lp-project-412_53wp6aN.jpg'],
	['Представительство Московского университета практической психологии в Мюнхене','Практическая психологии в Мюнхене',['services'],'//design.lpgenerator.ru/klient/uslugi/prakticheskaya-psihologiya-v-myunhene/','//media.lpgenerator.ru/images/303631/lp-project-413_uJTB6Ff.jpg'],
	['СИМАРГЛ','Разработка проектной документации для объектов культурного наследия',['services'],'//design.lpgenerator.ru/klient/uslugi/simargl/','//media.lpgenerator.ru/images/303631/lp-project-414_fiRie2o.jpg'],
	['PARKOMATIK','Удобная оплата городской парковки',['services'],'//design.lpgenerator.ru/klient/uslugi/parkomatik/','//media.lpgenerator.ru/images/303631/lp-project-415.jpg'],
	['ЭГИДА видеонаблюдение','Обезопасьте свой дом и бизнес с помощью комплектов видеонаблюдения',['services'],'//design.lpgenerator.ru/klient/uslugi/videonablyudenie_egida/','//media.lpgenerator.ru/images/303631/lp-project-416.jpg'],
	['Семейные путешествия','Туроператор семейного отдыха',['tourism'],'//design.lpgenerator.ru/klient/turizm/kompas-kemp/','//media.lpgenerator.ru/images/303631/lp-project-417.jpg'],
	['ORANGE life solutions','Доступная недвижимость Северного Кипра',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/nedvizhimost-na-kipre/','//media.lpgenerator.ru/images/303631/lp-project-418.jpg'],
	['Финансовый консультант','Услуги по негосударственному пенсионному страхованию',['services'],'//design.lpgenerator.ru/klient/uslugi/uslugi-po-negosudarstvennomu-pensionnomu-strahovaniyu/','//media.lpgenerator.ru/images/301342/lp-project-419_Z0fmmUi.jpg'],
	['ИНЖПЛАСТ','Сварочное оборудование для труб ПНД',['product'],'//design.lpgenerator.ru/klient/tovari/svarochnoe-oborudovanie/','//media.lpgenerator.ru/images/301342/lp-project-420_K3M2rpp.jpg'],
	['Врач остеопат Гудель Максим','Избавление от болей в позвоночнике за 3 дня',['services'],'//design.lpgenerator.ru/klient/uslugi/osteopat-gudel/','//media.lpgenerator.ru/images/301342/lp-project-421_7HavMCZ.jpg'],
	['PROFILL DOORS','Межкомнатные и входные двери в г. Москве и области',['product'],'//design.lpgenerator.ru/klient/tovari/profil-doors/','//media.lpgenerator.ru/images/301342/lp-project-422_iRQPXv7.jpg'],
	['Стальная линия','Входные двери от произодителя "Стальная линия"',['product'],'//design.lpgenerator.ru/klient/tovari/stalnaya-liniya/','//media.lpgenerator.ru/images/301342/lp-project-423_26htmwW.jpg'],
	['Vivein Momento','Авторский онлайн-курс MINDFULNESS по практической психологии',['services'],'//design.lpgenerator.ru/klient/uslugi/psiholog-konsultant/','//media.lpgenerator.ru/images/301342/lp-project-424_HJhm1ah.jpg'],
	['Che Vector','Монтаж и изготовление наружной рекламы',['services'],'//design.lpgenerator.ru/klient/uslugi/chevestor/','//media.lpgenerator.ru/images/301342/lp-project-425_JcPo9eb.jpg'],
	['Vyuga','Крупный производитель меховых шуб, аксессуаров из кожи и меха',['product'],'//design.lpgenerator.ru/klient/tovari/vyuga/','//media.lpgenerator.ru/images/301342/lp-project-426_Q5A7Buo.jpg'],
	['Holz Fabrik','Строительство деревянных домов из клеенного бруса',['realty'],'//design.lpgenerator.ru/klient/nedvizimost/stroitelstvo-domov-iz-brusa/','//media.lpgenerator.ru/images/301342/lp-project-427_5FfyfG7.jpg'],
	['Red Holt','Приписка и регистрация вагонов',['services'],'//design.lpgenerator.ru/klient/uslugi/pripiska-i-registratsiya-vagonov-red-holt/','//media.lpgenerator.ru/images/301342/lp-project-428_OtIJzcX.jpg'],
	['ОСТ','Общественное спортивное телевидение',['services'],'//design.lpgenerator.ru/klient/uslugi/ost/','//media.lpgenerator.ru/images/301342/lp-project-429_ZO6UXLu.jpg'],
	['TEPLOPANEL','Водяные потолочные лучистые отопители ',['services'],'//design.lpgenerator.ru/klient/uslugi/teplopanel/','//media.lpgenerator.ru/images/301342/lp-project-430_VauiHVe.jpg'],
	['GIC Canada','Начните новую жизнь в Канаде',['services'],'//design.lpgenerator.ru/klient/uslugi/gic-canada/','//media.lpgenerator.ru/images/301342/lp-project-431_GkOiBBZ.jpg'],
	['MINI-PARTY','Организация детских праздников',['services'],'//design.lpgenerator.ru/klient/uslugi/detskie-prazdniki/','//media.lpgenerator.ru/images/301342/lp-project-432_4lCE2W0.jpg'],
	['Vyuga','Ярмарка меховых изделий',['product'],'//design.lpgenerator.ru/klient/tovari/vyuga-yarmarka-shub/','//media.lpgenerator.ru/images/301342/lp-project-433_8fkm0q9.jpg'],
	['Shtorki Online','Подбор, производство и монтаж солнцезащитных систем',['product'],'//design.lpgenerator.ru/klient/tovari/zhalyuzi/','//media.lpgenerator.ru/images/301342/lp-project-434_3raZbTk.jpg'],
	['Garant Osvita','Набор студентов в украинский ВУЗ',['services'],'//design.lpgenerator.ru/klient/uslugi/garant-osvita/','//media.lpgenerator.ru/images/301342/lp-project-435_sREI5F9.jpg'],
	['Бамбук','Фабрика одежды для новорожденных',['product'],'//design.lpgenerator.ru/klient/tovari/novorozhdennyye/','//media.lpgenerator.ru/images/301342/lp-project-436.jpg'],
	['ORCA OPTIMA','Смесители ORCA OPTIMA от российского производителя',['product'],'//design.lpgenerator.ru/klient/tovari/orca-optima/','//media.lpgenerator.ru/images/301342/lp-project-437.jpg'],
	['Alpeneuro','Заказ такси из отеля до аэропорта',['services'],'//design.lpgenerator.ru/klient/uslugi/oteli/','//media.lpgenerator.ru/images/301342/lp-project-438.jpg'],
	['ПОЛЕТАЕВ КАРГО','Авиадоставка груза из Китая в Россию и Беларусь',['trucking'],'//design.lpgenerator.ru/klient/uslugi/kargo/','//media.lpgenerator.ru/images/301342/lp-project-439.jpg']
];

for(var i = 0; i < projects.length; i++) projects[i].push(i);

projects = projects.reverse();
